// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpHo5B8duaEi4ZbBMPpA7Gi2yqjn5Hfvk',
    appId: '1:916390778571:web:7db9c32b91655f0fecad4e',
    messagingSenderId: '916390778571',
    projectId: 'crudempoleesfirebase',
    authDomain: 'crudempoleesfirebase.firebaseapp.com',
    storageBucket: 'crudempoleesfirebase.appspot.com',
    measurementId: 'G-60HYQK2Q6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBMWR_5XlHelgu--hyakrQzjhBd0O9W08',
    appId: '1:916390778571:android:ba38600335476a97ecad4e',
    messagingSenderId: '916390778571',
    projectId: 'crudempoleesfirebase',
    storageBucket: 'crudempoleesfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBve3olse5BvNxq_YBLv4-OtvfJbkkDYLE',
    appId: '1:916390778571:ios:c8660acd91ac975fecad4e',
    messagingSenderId: '916390778571',
    projectId: 'crudempoleesfirebase',
    storageBucket: 'crudempoleesfirebase.appspot.com',
    iosBundleId: 'com.example.crudEmployeesFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBve3olse5BvNxq_YBLv4-OtvfJbkkDYLE',
    appId: '1:916390778571:ios:c8660acd91ac975fecad4e',
    messagingSenderId: '916390778571',
    projectId: 'crudempoleesfirebase',
    storageBucket: 'crudempoleesfirebase.appspot.com',
    iosBundleId: 'com.example.crudEmployeesFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpHo5B8duaEi4ZbBMPpA7Gi2yqjn5Hfvk',
    appId: '1:916390778571:web:e627d3981a9776aeecad4e',
    messagingSenderId: '916390778571',
    projectId: 'crudempoleesfirebase',
    authDomain: 'crudempoleesfirebase.firebaseapp.com',
    storageBucket: 'crudempoleesfirebase.appspot.com',
    measurementId: 'G-JTV6TGG7D0',
  );
}
